# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-gb
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content

# Uncomment the lines below to configure your website in a second language.
# zh-hant:
 # languageCode: zh-hant
 # contentDir: content/zh-hant
 # title: 蘇致霖
 # params:
 #   description: 蘇致霖的學術個人網頁。
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
